import 'package:http/http.dart' as http;
import 'dart:convert';

class NewsProviders {
  Uri uri = Uri.parse(
      "https://ot113tt778.execute-api.us-east-2.amazonaws.com/staging/store/list/{${2}}");

  Future<List<TempStore>> getNews() async {
    List<TempStore> news = [];

    final response = await http.get(uri);

    if (response.statusCode == 200) {
      Autogenerated data = Autogenerated.fromJson(jsonDecode(response.body));
      print(jsonDecode(response.body)['body']);
      news = jsonDecode(response.body)['body']['data']['store']
          .map<TempStore>((article) {
        return TempStore.fromJson(article);
      }).toList();
    }

    return news;
  }
}

class Autogenerated {
  bool? success;
  Data? data;

  Autogenerated({this.success, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  List<TempStore>? store;

  Data({this.store});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['store'] != null) {
      store = <TempStore>[];
      json['store'].forEach((v) {
        store!.add(new TempStore.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.store != null) {
      data['store'] = this.store!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class TempStore {
  int? id;
  int? ownerId;
  String? name;
  String? store_name;
  String? store_logo;
  int? status;
  int? inspection_status;
  int? open_yn;

  TempStore({
    this.id,
    this.ownerId,
    this.name,
    this.store_name,
    this.store_logo,
    this.status,
    this.inspection_status,
    this.open_yn,
  });

  TempStore.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    ownerId = json['owner_id'];
    name = json['name'];
    store_name = json['store_name'];
    store_logo = json['store_logo'];
    status = json['status'];
    inspection_status = json['inspection_status'];
    open_yn = json['open_yn'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['owner_id'] = this.ownerId;
    data['name'] = this.name;
    data['store_name'] = this.store_name;
    data['store_logo'] = this.store_logo;
    data['status'] = this.status;
    data['inspection_status'] = this.inspection_status;
    data['open_yn'] = this.open_yn;
    return data;
  }
}
