import 'dart:convert';
import 'package:json_annotation/json_annotation.dart';

part 'store_post_response.g.dart';

@JsonSerializable()
class StorePostResponse {
  int statusCode;
  int store_id;
  String store_logo_url;
  List<String> store_photo_urls;
  PresignedUrl? presignedUrl;

  StorePostResponse(
      {required this.statusCode,
      required this.store_id,
      required this.store_logo_url,
      required this.store_photo_urls});

  factory StorePostResponse.fromJson(Map<String, dynamic> json) =>
      _$StorePostResponseFromJson(json);
  Map<String, dynamic> toJson() => _$StorePostResponseToJson(this);
}

@JsonSerializable()
class PresignedUrl {
  String? logo;
  List<String>? storePhoto;

  PresignedUrl({this.logo, this.storePhoto});

  PresignedUrl.fromJson(Map<String, dynamic> json) {
    logo = json['logo'];
    storePhoto = json['store_photo'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['logo'] = this.logo;
    data['store_photo'] = this.storePhoto;
    return data;
  }
}

// class Autogenerated {
//   String? statusCode;
//   String? storeID;
//   PresignedUrl? presignedUrl;

//   Autogenerated({this.statusCode, this.storeID, this.presignedUrl});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     statusCode = json['statusCode'];
//     storeID = json['store_ID'];
//     presignedUrl = json['presigned_url'] != null
//         ? new PresignedUrl.fromJson(json['presigned_url'])
//         : null;
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['statusCode'] = this.statusCode;
//     data['store_ID'] = this.storeID;
//     if (this.presignedUrl != null) {
//       data['presigned_url'] = this.presignedUrl!.toJson();
//     }
//     return data;
//   }
// }

