import 'package:json_annotation/json_annotation.dart';

part 'store_post_response.g.dart';

@JsonSerializable()
class StorePhoto {
  String image_key;
  String put_url;

  StorePhoto({required this.image_key, required this.put_url});

  factory StorePhoto.fromJson(Map<String, dynamic> json) =>
      _$StorePhotoFromJson(json);
  Map<String, dynamic> toJson() => _$StorePhotoToJson(this);
}

@JsonSerializable()
class StorePostResponse {
  @JsonKey(defaultValue: 200)
  int statusCode;
  int store_id;
  String? store_logo_put_url;
  List<StorePhoto> store_photos;
  PresignedUrl? presignedUrl;
  String? bankBook_put_url;
  String? business_put_url;

  StorePostResponse(
      {required this.statusCode,
      required this.store_id,
      this.store_logo_put_url,
      required this.store_photos,
      this.bankBook_put_url,
      this.business_put_url});

  factory StorePostResponse.fromJson(Map<String, dynamic> json) =>
      _$StorePostResponseFromJson(json);
  Map<String, dynamic> toJson() => _$StorePostResponseToJson(this);
}

@JsonSerializable()
class StoreUpdateResponse {
  @JsonKey(defaultValue: 200)
  int statusCode;
  String msg;
  List<StorePhoto> store_photos;
  List<String> store_photo_get_urls;

  StoreUpdateResponse(
      {required this.statusCode,
      required this.msg,
      required this.store_photos,
      required this.store_photo_get_urls});

  factory StoreUpdateResponse.fromJson(Map<String, dynamic> json) =>
      _$StoreUpdateResponseFromJson(json);
  Map<String, dynamic> toJson() => _$StoreUpdateResponseToJson(this);
}

@JsonSerializable()
class PresignedUrl {
  String? logo;
  List<String>? storePhoto;

  PresignedUrl({this.logo, this.storePhoto});

  PresignedUrl.fromJson(Map<String, dynamic> json) {
    logo = json['logo'];
    storePhoto = json['store_photo'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['logo'] = logo;
    data['store_photo'] = storePhoto;
    return data;
  }
}

// class Autogenerated {
//   String? statusCode;
//   String? storeID;
//   PresignedUrl? presignedUrl;

//   Autogenerated({this.statusCode, this.storeID, this.presignedUrl});

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     statusCode = json['statusCode'];
//     storeID = json['store_ID'];
//     presignedUrl = json['presigned_url'] != null
//         ? new PresignedUrl.fromJson(json['presigned_url'])
//         : null;
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['statusCode'] = this.statusCode;
//     data['store_ID'] = this.storeID;
//     if (this.presignedUrl != null) {
//       data['presigned_url'] = this.presignedUrl!.toJson();
//     }
//     return data;
//   }
// }
