// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'flavors.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_mock.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Mock mode uses dev Firebase configuration
    if (F.isMock) {
      if (kIsWeb) {
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for web - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return androidDev;
        case TargetPlatform.iOS:
          return iosDev;
        case TargetPlatform.macOS:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for macos - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        case TargetPlatform.windows:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for windows - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }

    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions androidDev = FirebaseOptions(
    apiKey: 'AIzaSyBtFLsEuL770bVt6HQ0dbOgo5hDkNaoYqs',
    appId: '1:299419302046:android:0dac4e0605c6038d31a38f',
    messagingSenderId: '299419302046',
    projectId: 'cafe-owner',
    storageBucket: 'cafe-owner.appspot.com',
  );

  static const FirebaseOptions iosDev = FirebaseOptions(
    apiKey: 'AIzaSyBqwPQocNYiSEqlZNkAGDCtuj-N7QaQDoA',
    appId: '1:299419302046:ios:b053be5dde0c51eb31a38f',
    messagingSenderId: '299419302046',
    projectId: 'cafe-owner',
    storageBucket: 'cafeplatform.firebasestorage.app',
    iosBundleId: 'com.gifnut.owner.dev',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEboIUnDEP5HK0Nfm8jQZSBpd_7OZN8io',
    appId: '1:299419302046:web:c7f7e0761449357731a38f',
    messagingSenderId: '299419302046',
    projectId: 'cafe-owner-mock',
    authDomain: 'cafe-owner-mock.firebaseapp.com',
    storageBucket: 'cafe-owner-mock.appspot.com',
    measurementId: 'G-BC0NXY38TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtFLsEuL770bVt6HQ0dbOgo5hDkNaoYqs',
    appId: '1:299419302046:android:6329efd59877c18c31a38f',
    messagingSenderId: '299419302046',
    projectId: 'cafe-owner-mock',
    storageBucket: 'cafe-owner-mock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqwPQocNYiSEqlZNkAGDCtuj-N7QaQDoA',
    appId: '1:299419302046:ios:11635d89077a949531a38f',
    messagingSenderId: '299419302046',
    projectId: 'cafe-owner-mock',
    storageBucket: 'cafe-owner-mock.appspot.com',
    iosClientId:
        '299419302046-048r5pcbf61n9vjvvlrug4j1nbrahkn9.apps.googleusercontent.com',
    iosBundleId: 'com.gifnut.owner.mock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqwPQocNYiSEqlZNkAGDCtuj-N7QaQDoA',
    appId: '1:299419302046:ios:11635d89077a949531a38f',
    messagingSenderId: '299419302046',
    projectId: 'cafe-owner-mock',
    storageBucket: 'cafe-owner-mock.appspot.com',
    iosClientId:
        '299419302046-048r5pcbf61n9vjvvlrug4j1nbrahkn9.apps.googleusercontent.com',
    iosBundleId: 'com.gifnut.owner.mock',
  );
}