import 'package:http/http.dart' as http;
import 'dart:convert';

class Autogenerated {
  String? id;
  String? uid;
  String? password;
  String? phone;
  String? name;
  String? bankbook;

  Autogenerated(
      {this.id, this.uid, this.password, this.phone, this.name, this.bankbook});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    uid = json['uid'];
    password = json['password'];
    phone = json['phone'];
    name = json['name'];
    bankbook = json['bankbook'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['uid'] = this.uid;
    data['password'] = this.password;
    data['phone'] = this.phone;
    data['name'] = this.name;
    data['bankbook'] = this.bankbook;
    return data;
  }
}
