import 'package:http/http.dart' as http;
import 'dart:convert';

class StoreListProviders {
  Uri uri = Uri.parse(
      "https://ot113tt778.execute-api.us-east-2.amazonaws.com/staging/store/list/${2}");

  Future<List<TempStore>> getNews() async {
    List<TempStore> news = [];

    final response = await http.get(uri);

    if (response.statusCode == 200) {
      news =
          jsonDecode(response.body)['body']['store'].map<TempStore>((article) {
        return TempStore.fromJson(article);
      }).toList();
    }

    print("in provider2");
    print(news);
    return news;
  }
}

class Autogenerated {
  int? statusCode;
  Body? body;

  Autogenerated({this.statusCode, this.body});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode'];
    body = json['body'] != null ? new Body.fromJson(json['body']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['statusCode'] = this.statusCode;
    if (this.body != null) {
      data['body'] = this.body!.toJson();
    }
    return data;
  }
}

class Body {
  List<TempStore>? tempStore;

  Body({this.tempStore});

  Body.fromJson(Map<String, dynamic> json) {
    if (json['TempStore'] != null) {
      tempStore = <TempStore>[];
      json['TempStore'].forEach((v) {
        tempStore!.add(new TempStore.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.tempStore != null) {
      data['TempStore'] = this.tempStore!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class TempStore {
  int? ownerId;
  int? storeId;
  String? storeName;
  String? storeLogo;
  int? status;
  int? inspectionStatus;
  int? openYn;

  TempStore(
      {this.ownerId,
      this.storeId,
      this.storeName,
      this.storeLogo,
      this.status,
      this.inspectionStatus,
      this.openYn});

  TempStore.fromJson(Map<String, dynamic> json) {
    ownerId = json['owner_id'];
    storeId = json['store_id'];
    storeName = json['store_name'];
    storeLogo = json['store_logo'];
    status = json['status'];
    inspectionStatus = json['inspection_status'];
    openYn = json['open_yn'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['owner_id'] = this.ownerId;
    data['store_id'] = this.storeId;
    data['store_name'] = this.storeName;
    data['store_logo'] = this.storeLogo;
    data['status'] = this.status;
    data['inspection_status'] = this.inspectionStatus;
    data['open_yn'] = this.openYn;
    return data;
  }
}
